name: CI

on:
  push:
    paths-ignore:
    - '**.md'

  pull_request:
    branches:
    - master
    paths-ignore:
    - '**.md'

env:
  FAISS_VERSION: 1.7.1

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build
      run: dotnet build --configuration Release

    - name: Pack
      run: dotnet pack --configuration Release --no-build --output ./nuget-packages ./SpaceHosting.Index/SpaceHosting.Index.csproj

    - name: Test
      run: |
        docker container run --rm \
            --volume $PWD/lib-faiss-native:/host \
            ghcr.io/${{ github.repository_owner }}/space-hosting/faiss-lib:$FAISS_VERSION \
            bash -c 'cp /lib-faiss-native/* /host/'

        export LD_LIBRARY_PATH=$PWD/lib-faiss-native
        dotnet test --configuration Release --no-build --verbosity normal
